# Generated by Django 2.2.5 on 2019-12-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TashkentBoard',
            fields=[
                ('id_board', models.AutoField(db_column='ID_BOARD', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'tashkent_boards',
            },
        ),
        migrations.CreateModel(
            name='TashkentMember',
            fields=[
                ('id_member', models.AutoField(db_column='ID_MEMBER', primary_key=True, serialize=False)),
                ('membername', models.CharField(db_column='memberName', max_length=80)),
                ('dateregistered', models.PositiveIntegerField(db_column='dateRegistered')),
                ('posts', models.PositiveIntegerField()),
                ('realname', models.CharField(db_column='realName', max_length=255)),
                ('emailaddress', models.CharField(db_column='emailAddress', max_length=64)),
            ],
            options={
                'db_table': 'tashkent_members',
            },
        ),
        migrations.CreateModel(
            name='TashkentMessage',
            fields=[
                ('id_msg', models.AutoField(db_column='ID_MSG', primary_key=True, serialize=False)),
                ('postertime', models.PositiveIntegerField(db_column='posterTime')),
                ('id_msg_modified', models.PositiveIntegerField(db_column='ID_MSG_MODIFIED')),
                ('subject', models.TextField()),
                ('postername', models.TextField(db_column='posterName')),
                ('posteremail', models.TextField(db_column='posterEmail')),
                ('modifiedtime', models.PositiveIntegerField(db_column='modifiedTime')),
                ('modifiedname', models.TextField(db_column='modifiedName')),
                ('body', models.TextField()),
                ('id_board', models.ForeignKey(db_column='ID_BOARD', on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentBoard')),
                ('id_member', models.ForeignKey(db_column='ID_MEMBER', on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentMember')),
            ],
            options={
                'db_table': 'tashkent_messages',
            },
        ),
        migrations.CreateModel(
            name='TashkentTopic',
            fields=[
                ('id_topic', models.AutoField(db_column='ID_TOPIC', primary_key=True, serialize=False)),
                ('id_board', models.ForeignKey(db_column='ID_BOARD', on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentBoard')),
                ('id_first_msg', models.ForeignKey(db_column='ID_FIRST_MSG', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics_first', to='board.TashkentMessage')),
                ('id_last_msg', models.ForeignKey(db_column='ID_LAST_MSG', on_delete=django.db.models.deletion.DO_NOTHING, related_name='topics_last', to='board.TashkentMessage')),
                ('id_member_started', models.ForeignKey(db_column='ID_MEMBER_STARTED', on_delete=django.db.models.deletion.DO_NOTHING, related_name='started_topics', to='board.TashkentMember')),
            ],
            options={
                'db_table': 'tashkent_topics',
            },
        ),
        migrations.AddField(
            model_name='tashkentmessage',
            name='id_topic',
            field=models.ForeignKey(db_column='ID_TOPIC', on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentTopic'),
        ),
    ]
