# Generated by Django 3.0.5 on 2020-04-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.PositiveIntegerField(db_column='type')),
                ('object_id_in_contest', models.PositiveIntegerField(db_column='id_in_contest')),
                ('object_name', models.TextField(db_column='name')),
            ],
            options={
                'db_table': '_identifiers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('parent_msg_id', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('date_created', models.PositiveIntegerField()),
                ('subject', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentMember')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentBoard')),
                ('identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='board.Identifier')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.TashkentTopic')),
            ],
            options={
                'db_table': '_messages',
            },
        ),
    ]
